version: "3.7"
services:
  selenoid:
    networks:
      - backend
    hostname: selenoid
    restart: always
    image: aerokube/selenoid:1.9.2
    command: -limit 4 -retry-count 1000 -container-network infra_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/selenoid/browsers.json:/etc/selenoid/browsers.json
      - ${PWD}/selenoid/video:/opt/selenoid/video
      - ${PWD}/selenoid/logs:/opt/selenoid/logs
    ports:
      - "4444:4444"

  gitlab:
    networks:
      - backend
    restart: always
    image: gitlab/gitlab-ce:latest
    hostname: ${GITLAB_HOST}
    volumes:
      - ${PWD}/gitlab/config:/etc/gitlab
      - ${PWD}/gitlab/logs:/var/log/gitlab
      - ${PWD}/gitlab/data:/var/opt/gitlab
    ports:
      - "${GITLAB_TLS_PORT}:443"
      - "${GITLAB_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    environment:
      - OMNIBUS_GITLAB_CONFIG="external_url http://localhost"
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}

  gitlab-runner:
    networks:
      - backend
    hostname: gitlab-runner
    restart: always
    image: gitlab/gitlab-runner
    volumes: ["${PWD}/gitlab/runner:/etc/gitlab-runner", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    environment:
      - CI_SERVER_URL=https://${GITLAB_HOST}/
    depends_on:
      - gitlab
    links:
      - gitlab

  register-runner:
    networks:
      - backend
    restart: 'no'
    image: gitlab/gitlab-runner:alpine
    volumes:
      - "${PWD}/gitlab/runner:/etc/gitlab-runner"
      - /var/run/docker.sock:/var/run/docker.sock
    command:
    - register
    - --non-interactive
    - --locked=false
    - --name="Python Runner"
    - --executor=docker
    - --docker-image=python:3.7
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    - --tag-list="python"
    - --docker-network-mode="bridge"
    environment:
    - CI_SERVER_URL=http://${GITLAB_HOST}/
    - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
    depends_on:
      - gitlab
    links:
      - gitlab

  allure:
    networks:
      - backend
    restart: always
    hostname: allure
    image: frankescobar/allure-docker-service
    ports:
      - "4040:4040"
      - "5050:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY="TRUE"
    volumes:
      - ${PWD}/allure-results:/app/allure-results

  selenoid-ui:
    networks:
      - backend
    hostname: selenoid-ui
    restart: always
    image: aerokube/selenoid-ui
    ports:
      - "9090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    links:
      - selenoid
networks:
  backend: