version: "3.7"
services:
  selenoid:
    network_mode: bridge
    hostname: selenoid
    restart: always
    image: aerokube/selenoid:1.9.2
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/config:/etc/selenoid/
      - ./selenoid/video:/opt/selenoid/video
      - ./selenoid/logs:/opt/selenoid/logs
    ports:
      - "4444:4444"

  gitlab:
    network_mode: bridge
    restart: always
    image: gitlab/gitlab-ce:latest
    hostname: ${GITLAB_HOST}
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - "${GITLAB_TLS_PORT}:443"
      - "${GITLAB_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    environment:
      - OMNIBUS_GITLAB_CONFIG="external_url http://localhost"
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
    networks:
      - backend

  gitlab-runner:
    hostname: gitlab-runner
    restart: always
    image: gitlab/gitlab-runner
    volumes: ["./gitlab/runner:/etc/gitlab-runner", "//var/run/docker.sock:/var/run/docker.sock:rw"]
    environment:
      - CI_SERVER_URL=https://${GITLAB_HOST}/
    networks:
      - backend
    depends_on:
      - gitlab
    links:
      - gitlab

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:alpine
    volumes:
    - "./gitlab/runner:/etc/gitlab-runner"
    command:
    - register
    - --non-interactive
    - --locked=false
    - --name="Python Runner"
    - --executor=docker
    - --docker-image=python:latest
    - --docker-volumes=//var/run/docker.sock:/var/run/docker.sock
    - --tag-list="docker,python"
    - --docker-network-mode="infra_backend"
    environment:
    - CI_SERVER_URL=http://${GITLAB_HOST}/
    - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
    networks:
      - backend
    depends_on:
      - gitlab
    links:
      - gitlab

  allure:
    network_mode: bridge
    restart: always
    hostname: allure
    image: frankescobar/allure-docker-service
    ports:
      - "4040:4040"
      - "5050:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY="TRUE"
    volumes:
      - ./allure-results:/app/allure-results

  selenoid-ui:
    network_mode: bridge
    hostname: selenoid-ui
    restart: always
    image: aerokube/selenoid-ui
    ports:
      - "9090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    links:
      - selenoid

networks:
  backend:

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner: