version: "3.7"
services:
  selenoid:
    networks:
      - backend
    hostname: selenoid
    restart: always
    image: aerokube/selenoid:1.9.2
    command: -limit 4 -retry-count 1000 -container-network infra_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/selenoid/browsers.json:/etc/selenoid/browsers.json
      - ${PWD}/selenoid/video:/opt/selenoid/video
      - ${PWD}/selenoid/logs:/opt/selenoid/logs
    ports:
      - "4444:4444"

  allure:
    networks:
      - backend
    restart: always
    hostname: allure
    image: frankescobar/allure-docker-service
    ports:
      - "4040:4040"
      - "5050:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY="TRUE"
    volumes:
      - ${PWD}/allure-results:/app/allure-results

  selenoid-ui:
    networks:
      - backend
    hostname: selenoid-ui
    restart: always
    image: aerokube/selenoid-ui
    ports:
      - "9090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    links:
      - selenoid
networks:
  backend: