concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "\"Python Runner\""
  url = "http://gitlab/"
  token = "MAnezzKhNQs3qBaVHFPp"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "python:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    network_mode="infra_backend"

    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
